[modules]
left = [ "Clock", "Workspaces" ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [ "Privacy", "Settings" ] ]

[workspaces]
disable_special_workspaces = true

[settings]
# lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "iwgtk"
# vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"
remove_airplane_btn = true
remove_idle_btn = true
indicators = ["Battery", "Bluetooth", "Network", "Audio"]
enable_esc_key = true
